import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster as SoonerToast } from "@/components/ui/sonner";
import LayoutProvider from "@/static-data/layout-provider";
import { auth } from "@/static-data/auth";
import AuthProvider from "@/static-data/auth-provider";
import SessionProvider from "@/static-data/session-provider";
import CartPopup from "@/static-data/cartpopup";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en">
      <body>
        <div
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <AuthProvider>
            <SessionProvider session={session}>
              <LayoutProvider>{children}</LayoutProvider>
              <CartPopup />
              <SoonerToast />
            </SessionProvider>
          </AuthProvider>
        </div>
      </body>
    </html>
  );
}
